### ISSUE TITLE
Automatically set extraheader for both with and without ".git"

### ISSUE THREAD

**Issue by sksat** [arkedge/gh-federation#54]
The gh-federation client uses Git's extraheader to automatically checkout the specified repository via gh-federation.
This configuration should specify the exact remote URL to be used for the actual checkout.

Therefore, the current implementation causes inconvenience in the following case.

```yaml
- uses: arkedge/gh-federation@v4.0.0
  with:
    endpoint: ${{ secrets.GH_FEDERATION_ENDPOINT }}
    repos: |
      <your-oug>/<something-internal-repository>

- uses: actions/checkout@v4
  with:
    # "https://github.com/<your-oug>/<something-internal-repository>.git" is in the .gitmodules
    submodules: recursive
```

In this example, the extraheader is set for the remote URL `https://<your-oug>/<something-internal-repository>`, but the actual checkout is set for `https://<your-oug>/<something-internal-repository>.git`, the checkout via gh-federation fails.
